cache:
  bundler: true
  yarn: true
  directories:
    - Carthage
    - ~/.swiftenv
    - .build

stages:
  - name: "Test"
    if: tag IS NOT present
  - name: "Deploy"
    if: tag IS present

_base_envs:
  # Bases
- &macos_env
  os: osx
  language: objective-c
  osx_image: xcode10.2
- &macos_beta_env
  <<: *macos_env
  osx_image: xcode11
- &xcode_env
  <<: *macos_env
  xcode_project: Partial.xcodeproj
  after_success:
    - bash <(curl -s https://codecov.io/bash)
- &xcode_beta_env
  <<: *xcode_env
  <<: *macos_beta_env
- &swiftenv_install
  before_install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
- &linux_env
  <<: *swiftenv_install
  os: linux
  language: generic

  # Deployment OSs
- &macos_xcode_env
  <<: *xcode_env
  install: carthage bootstrap --platform macOS --cache-builds
  xcode_scheme: Partial-macOS
  xcode_destination: platform=macOS
- &macos_xcode_beta_env
  <<: *macos_xcode_env
  <<: *xcode_beta_env
- &ios_xcode_env
  <<: *xcode_env
  install: carthage bootstrap --platform iOS --cache-builds
  xcode_scheme: Partial-iOS
  xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone XS
- &ios_xcode_beta_env
  <<: *ios_xcode_env
  <<: *xcode_beta_env
  xcode_destination: platform=iOS Simulator,OS=13,name=iPhone XS
- &tvos_xcode_env
  <<: *xcode_env
  install: carthage bootstrap --platform tvOS --cache-builds
  xcode_scheme: Partial-tvOS
  xcode_destination: platform=tvOS Simulator,OS=12.2,name=Apple TV 4K
- &tvos_xcode_beta_env
  <<: *tvos_xcode_env
  <<: *xcode_beta_env
  xcode_destination: platform=tvOS Simulator,OS=13,name=Apple TV 4K

jobs:
  include:
    - <<: *macos_env
      stage: "Test"
      name: "Danger"
      if: type = pull_request
      addons:
        homebrew:
          packages:
            - yarn
      install:
        - yarn install
        - swift build --skip-update --target CIDependencies
        - swift build --skip-update --product danger-swift
      script: swift run --skip-update danger-swift ci --danger-js-path $(yarn bin danger) --verbose

    - <<: *macos_env
      stage: "Test"
      name: "pod lib lint"
      if: type = pull_request
      install: bundle install --deployment
      script: bundle exec pod lib lint

    - <<: *macos_env
      stage: "Test"
      name: "Unit tests (macOS, SwiftPM)"
      if: type != pull_request
      script: swift test

    - <<: *macos_beta_env
      stage: "Test"
      name: "Unit tests (macOS, Xcode Beta, SwiftPM)"
      if: type != pull_request
      script: swift test

    - <<: *ios_xcode_env
      stage: "Test"
      name: "Unit tests (iOS, Xcode)"
      if: type != pull_request

    - <<: *ios_xcode_env
      stage: "Test"
      name: "Unit tests (iOS, Xcode Beta)"
      if: type != pull_request

    - <<: *macos_xcode_env
      stage: "Test"
      name: "Unit tests (macOS, Xcode)"
      if: type != pull_request

    - <<: *macos_xcode_env
      stage: "Test"
      name: "Unit tests (macOS, Xcode Beta)"
      if: type != pull_request

    - <<: *tvos_xcode_env
      stage: "Test"
      name: "Unit tests (tvOS, Xcode)"
      if: type != pull_request

    - <<: *tvos_xcode_env
      stage: "Test"
      name: "Unit tests (tvOS, Xcode Beta)"
      if: type != pull_request

    - <<: *linux_env
      stage: "Test"
      name: "Unit tests (linux, SwiftPM)"
      if: type != pull_request
      script: swift test

    - <<: *macos_env
      stage: "Deploy"
      name: "Upload Prebuilt Frameworks to GitHub"
      install: skip
      script: skip
      before_deploy: carthage build --archive --platform iOS,macOS,tvOS,watchOS
      deploy:
        provider: releases
        api_key: $GITHUB_ACCESS_TOKEN
        file: Partial.framework.zip
        skip_cleanup: true
        on:
          tags: true
          branch: master

    - <<: *macos_env
      stage: "Deploy"
      name: "CocoaPods release"
      install: bundle install --deployment
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: bundle exec pod trunk push
        on:
          tags: true
          branch: master

    - <<: *macos_env
      stage: "Deploy"
      name: "Upload docs to GitHub Pages"
      install: bundle install --deployment
      script: bundle exec jazzy
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs
        github_token: $GITHUB_ACCESS_TOKEN
        keep_history: true
        on:
          tags: true
          branch: master
